name: stax
description: stax command line tool for git
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  path: ^1.8.3
  collection: ^1.18.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.6
  test_api: ^0.6.1
  meta: ^1.11.0
