name: stax
description: stax command line tool for git
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:
  path: 1.9.0
  cli_util: 0.4.1
  collection: 1.19.0
  http: 1.2.2
  characters: ^1.4.1

dev_dependencies:
  lints: 4.0.0
  test: 1.25.8
  test_api: 0.7.3
  meta: 1.15.0
