on:
  push:
    branches: [ "main" ]
    paths:
      DART_SDK_VERSION

jobs:
  dart-sdk-version-trigger:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: get-version
        run: echo "dart_sdk_version=$(cat DART_SDK_VERSION)" >> $GITHUB_OUTPUT
      - run: |
          sed -i "s+sdk: ^.*+sdk: ^$DART_SDK_VERSION+" ./cli/pubspec.yaml
        env:
          DART_SDK_VERSION: ${{ steps.get-version.outputs.dart_sdk_version }}
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ steps.get-version.outputs.dart_sdk_version }}
      - run: dart pub get
        working-directory: cli
      - run: dart test
        working-directory: cli
      - run: dart analyze
        working-directory: cli
      - run: |
          git config --global user.name 'stax'
          git config --global user.email 'stax@staxforgit.com'
          sed -i "s+sdk: ^.*+sdk: ^$DART_SDK_VERSION+" ./cli/pubspec.yaml
          sed -i "s+          sdk: .*+          sdk: $DART_SDK_VERSION+" ./.github/workflows/*
          git checkout -b update-dart-sdk-version-for-cli-to-$DART_SDK_VERSION
          git commit -a -m "Update dart sdk version for cli to $DART_SDK_VERSION"
          git push --set-upstream origin update-dart-sdk-version-for-cli-to-$DART_SDK_VERSION
          gh pr merge $(gh pr create -B main -f) --auto --squash
        env:
          GH_TOKEN: ${{ secrets.PAT }}
          DART_SDK_VERSION: ${{ steps.get-version.outputs.dart_sdk_version }}
      - run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/TarasMazepa/homebrew-stax/actions/workflows/update.yml/dispatches \
            -f "ref=main" -f "inputs[dart_sdk_version]=${{ steps.get-version.outputs.dart_sdk_version }}"
        env:
          GH_TOKEN: ${{ secrets.HOMEBREW_STAX_DISPATCH }}
      - run: |
          git checkout HEAD~
          sed -i "s+<dependency id='dart-sdk' version='.*' />+<dependency id='dart-sdk' version='$DART_SDK_VERSION' />+" ./chocolatey/stax/stax.nuspec
          git checkout -b chocolatey-update-dart-sdk-to-$DART_SDK_VERSION
          git commit -a -m "Chocolatey update dart sdk to $DART_SDK_VERSION"
          git push --set-upstream origin chocolatey-update-dart-sdk-to-$DART_SDK_VERSION
          gh pr merge $(gh pr create -B main -f) --auto --squash
        env:
          GH_TOKEN: ${{ secrets.PAT }}
          DART_SDK_VERSION: ${{ steps.get-version.outputs.dart_sdk_version }}
